### ISSUE TITLE
Readme.md description of custom open telnet command 

### ISSUE THREAD

**Issue by obs945** [niceboygithub/AqaraGateway#12]
Yesterday, I successfully enable telnet for my Aqara AirCondition P3.
Unfortunately I flashed the firmware according to zvldz's instruction and P3 became a brick.
I checked closed issue and found it's better just copy pubic mosquitto to /data/bin.
Since there is a better solution and in case not to see more tragedy, I suggest remove the description of flash modification firmwares in Readme.md.

My main purpose of Aqara AirCondition P3 is to use smart power plug/socket not gateway.
However, P3 can only use gateway and IR remote functions through Homekit.
And there is a quick question, can I integrate my new P3 smart power plug function into homekit through home assistant with the AqaraGateway ?

**Comment by niceboygithub** [comment]
> Yesterday, I successfully enable telnet for my Aqara AirCondition P3.
> Unfortunately I flashed the firmware according to zvldz's instruction and P3 became a brick.
> I checked closed issue and found it's better just copy pubic mosquitto to /data/bin.
> Since there is a better solution and in case not to see more tragedy, I suggest remove the description of flash modification firmwares in Readme.md.

No idea where you get the firmware for P3. There are customized firmwares for M1S and M2.
Now only M2 needs to use modified customize firmware to use this component.
For P3, there are two steps to use this component.
1. Enable telnet (following  zvldz's instruction)
2. Have mosquitto as publice (copy public mosquitto  to /data/bin

> My main purpose of Aqara AirCondition P3 is to use smart power plug/socket not gateway.
> However, P3 can only use gateway and IR remote functions through Homekit.
> And there is a quick question, can I integrate my new P3 smart power plug function into homekit through home assistant with the AqaraGateway ?

I think there is a way to have power plug. But I do not have P3, can not study how to implement it.
Since P3 have miio protocol, I think that you can try these three custom_component
1. https://github.com/syssi/xiaomi_raw
2. https://github.com/ha0y/xiaomi_miot_raw
3. https://github.com/al-one/hass-xiaomi-miot

**Comment by rezmus** [comment]
my best guess is he flashed mgl03 kernel/rootfs to p3.

**Comment by niceboygithub** [comment]
> my best guess is he flashed mgl03 kernel/rootfs to p3.

If so, there is another slot of linux and rootfs for P3.
If he knows how to switch to another slot, P3 will be alive.
